// PEC (Posta Elettronica Certificata) receipt detection.
//
// Italian certified-email accounts receive, for every message sent/received, an
// automatic "ricevuta" (receipt) generated by the PEC provider ("gestore").
// These receipts:
//   - are sent FROM `posta-certificata@<gestore>` (e.g. posta-certificata@pec.aruba.it)
//   - have a SUBJECT starting with a receipt keyword (ACCETTAZIONE:, CONSEGNA:, …)
//
// IMPORTANT: the *real* incoming certified mail (the "busta di trasporto") also
// comes from posta-certificata@… but its subject starts with `POSTA CERTIFICATA:`.
// That is genuine mail and must NOT be treated as a receipt. Hence both the sender
// AND a receipt subject prefix are required, and `POSTA CERTIFICATA:` is excluded.

/** Address (local part) the PEC gestore uses to send receipts. */
export const PEC_RECEIPT_SENDER_PREFIX = "posta-certificata@";

/**
 * Subject prefixes (without the trailing colon) of the standard PEC receipt
 * types defined by the Italian PEC regulations (DPR 68/2005 and related rules).
 * Stored uppercase; matching is case-insensitive.
 */
export const RECEIPT_SUBJECT_PREFIXES = [
  "ACCETTAZIONE",
  "NON ACCETTAZIONE",
  "MANCATA ACCETTAZIONE",
  "PRESA IN CARICO",
  "AVVENUTA CONSEGNA",
  "CONSEGNA",
  "MANCATA CONSEGNA",
  "PREAVVISO DI MANCATA CONSEGNA",
  "ERRORE DI CONSEGNA",
  "ERRORE CONSEGNA",
  "ANOMALIA MESSAGGIO",
  "RILEVAZIONE VIRUS",
] as const;

/**
 * True when the given email address should be offered PEC mode — i.e. it looks
 * like a certified-email address (contains "pec", "legalmail", or "legal").
 */
export function isPecCandidateEmail(email: string | null | undefined): boolean {
  if (!email) return false;
  return /pec|legalmail|legal/i.test(email);
}

/**
 * True when a message (by sender + subject) is a PEC receipt that should be kept
 * out of the inbox and surfaced only in the "Ricevute" folder.
 */
export function isPecReceipt(
  fromAddress: string | null | undefined,
  subject: string | null | undefined,
): boolean {
  if (!fromAddress || !subject) return false;
  if (!fromAddress.toLowerCase().startsWith(PEC_RECEIPT_SENDER_PREFIX)) return false;
  const upper = subject.trim().toUpperCase();
  return RECEIPT_SUBJECT_PREFIXES.some((p) => upper.startsWith(`${p}:`));
}

/**
 * SQL boolean predicate (no bound params — uses only constant string literals)
 * matching the same receipts as {@link isPecReceipt}, for reuse in reconcile
 * UPDATE/DELETE statements and the smart-folder search builder.
 *
 * @param alias table alias whose `from_address` / `subject` columns to test.
 */
export function pecReceiptSqlPredicate(alias: string): string {
  // SQLite LIKE is case-insensitive for ASCII, so a lowercase sender pattern and
  // uppercase subject patterns match regardless of the stored casing.
  const senderCond = `LOWER(${alias}.from_address) LIKE '${PEC_RECEIPT_SENDER_PREFIX}%'`;
  const subjectConds = RECEIPT_SUBJECT_PREFIXES.map(
    (p) => `UPPER(${alias}.subject) LIKE '${p}:%'`,
  ).join(" OR ");
  return `(${senderCond} AND (${subjectConds}))`;
}
